In [82]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

import tensorflow
from tensorflow.keras.models import Sequential,load_model
from tensorflow.keras.layers import Dense


 

In [63]:
iris_data = load_iris() 

print('Example data: ')
print(iris_data.data[:5])
print('Example labels: ')
print(iris_data.target[:5])

Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Example labels: 
[0 0 0 0 0]


In [64]:
x = iris_data.data
y_ = iris_data.target.reshape(-1, 1)

In [65]:
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)

In [66]:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)

In [67]:
model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(10, activation='relu', name='fc2'))
model.add(Dense(3, activation='softmax', name='output'))

In [68]:
model.compile(optimizer = 'adam', loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())


Neural Network Model Summary: 
Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 fc1 (Dense)                 (None, 10)                50        
                                                                 
 fc2 (Dense)                 (None, 10)                110       
                                                                 
 output (Dense)              (None, 3)                 33        
                                                                 
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
None


In [72]:
model.fit(train_x, train_y, validation_data = (test_x,test_y), verbose=2, batch_size=5, epochs=200)

Epoch 1/200
24/24 - 0s - loss: 0.0484 - accuracy: 0.9833 - val_loss: 0.1240 - val_accuracy: 0.9667 - 129ms/epoch - 5ms/step
Epoch 2/200
24/24 - 0s - loss: 0.0476 - accuracy: 0.9917 - val_loss: 0.1195 - val_accuracy: 0.9667 - 41ms/epoch - 2ms/step
Epoch 3/200
24/24 - 0s - loss: 0.0498 - accuracy: 0.9750 - val_loss: 0.1198 - val_accuracy: 0.9667 - 36ms/epoch - 2ms/step
Epoch 4/200
24/24 - 0s - loss: 0.0486 - accuracy: 0.9833 - val_loss: 0.1289 - val_accuracy: 0.9667 - 40ms/epoch - 2ms/step
Epoch 5/200
24/24 - 0s - loss: 0.0472 - accuracy: 0.9833 - val_loss: 0.1139 - val_accuracy: 0.9667 - 39ms/epoch - 2ms/step
Epoch 6/200
24/24 - 0s - loss: 0.0440 - accuracy: 0.9833 - val_loss: 0.1366 - val_accuracy: 0.9667 - 37ms/epoch - 2ms/step
Epoch 7/200
24/24 - 0s - loss: 0.0492 - accuracy: 0.9833 - val_loss: 0.1253 - val_accuracy: 0.9667 - 40ms/epoch - 2ms/step
Epoch 8/200
24/24 - 0s - loss: 0.0471 - accuracy: 0.9917 - val_loss: 0.1189 - val_accuracy: 0.9667 - 39ms/epoch - 2ms/step
Epoch 9/200
24/

Epoch 68/200
24/24 - 0s - loss: 0.0417 - accuracy: 0.9833 - val_loss: 0.1356 - val_accuracy: 0.9667 - 47ms/epoch - 2ms/step
Epoch 69/200
24/24 - 0s - loss: 0.0504 - accuracy: 0.9750 - val_loss: 0.1483 - val_accuracy: 0.9667 - 42ms/epoch - 2ms/step
Epoch 70/200
24/24 - 0s - loss: 0.0466 - accuracy: 0.9833 - val_loss: 0.1356 - val_accuracy: 0.9667 - 36ms/epoch - 2ms/step
Epoch 71/200
24/24 - 0s - loss: 0.0402 - accuracy: 0.9833 - val_loss: 0.1474 - val_accuracy: 0.9667 - 38ms/epoch - 2ms/step
Epoch 72/200
24/24 - 0s - loss: 0.0424 - accuracy: 0.9833 - val_loss: 0.1412 - val_accuracy: 0.9667 - 39ms/epoch - 2ms/step
Epoch 73/200
24/24 - 0s - loss: 0.0417 - accuracy: 0.9833 - val_loss: 0.1312 - val_accuracy: 0.9667 - 41ms/epoch - 2ms/step
Epoch 74/200
24/24 - 0s - loss: 0.0434 - accuracy: 0.9833 - val_loss: 0.1587 - val_accuracy: 0.9667 - 39ms/epoch - 2ms/step
Epoch 75/200
24/24 - 0s - loss: 0.0496 - accuracy: 0.9833 - val_loss: 0.1336 - val_accuracy: 0.9667 - 38ms/epoch - 2ms/step
Epoch 76

Epoch 134/200
24/24 - 0s - loss: 0.0399 - accuracy: 0.9833 - val_loss: 0.1660 - val_accuracy: 0.9667 - 38ms/epoch - 2ms/step
Epoch 135/200
24/24 - 0s - loss: 0.0377 - accuracy: 0.9833 - val_loss: 0.1448 - val_accuracy: 0.9667 - 43ms/epoch - 2ms/step
Epoch 136/200
24/24 - 0s - loss: 0.0392 - accuracy: 0.9750 - val_loss: 0.1457 - val_accuracy: 0.9667 - 43ms/epoch - 2ms/step
Epoch 137/200
24/24 - 0s - loss: 0.0407 - accuracy: 0.9750 - val_loss: 0.1386 - val_accuracy: 0.9667 - 43ms/epoch - 2ms/step
Epoch 138/200
24/24 - 0s - loss: 0.0359 - accuracy: 0.9833 - val_loss: 0.1524 - val_accuracy: 0.9667 - 43ms/epoch - 2ms/step
Epoch 139/200
24/24 - 0s - loss: 0.0373 - accuracy: 0.9833 - val_loss: 0.1403 - val_accuracy: 0.9667 - 42ms/epoch - 2ms/step
Epoch 140/200
24/24 - 0s - loss: 0.0367 - accuracy: 0.9917 - val_loss: 0.1509 - val_accuracy: 0.9667 - 39ms/epoch - 2ms/step
Epoch 141/200
24/24 - 0s - loss: 0.0411 - accuracy: 0.9750 - val_loss: 0.1468 - val_accuracy: 0.9667 - 37ms/epoch - 2ms/step


Epoch 200/200
24/24 - 0s - loss: 0.0395 - accuracy: 0.9833 - val_loss: 0.1525 - val_accuracy: 0.9667 - 43ms/epoch - 2ms/step


In [73]:
model.save("ANN_model.h5")


In [75]:
classifier = load_model('ANN_model.h5')

In [77]:
predictions = classifier.predict(test_x)

In [78]:
print(predictions)

[[1.71663214e-05 9.98696864e-01 1.28605927e-03]
 [9.99991536e-01 8.50741162e-06 1.24814116e-16]
 [3.04719278e-10 1.04465063e-04 9.99895573e-01]
 [9.99991536e-01 8.48600303e-06 9.63867246e-17]
 [1.37902032e-06 9.99841213e-01 1.57293180e-04]
 [3.16338519e-05 9.99945283e-01 2.31043250e-05]
 [3.78256191e-05 9.99931097e-01 3.11355216e-05]
 [7.78983909e-12 3.40208608e-05 9.99966025e-01]
 [7.78093256e-10 9.93772555e-05 9.99900579e-01]
 [9.99980330e-01 1.97145291e-05 7.57935140e-16]
 [6.21624174e-09 2.91902223e-03 9.97080982e-01]
 [6.68653177e-09 2.93952948e-03 9.97060478e-01]
 [2.78597673e-10 4.12198278e-05 9.99958754e-01]
 [5.45185230e-08 1.08748516e-02 9.89125133e-01]
 [9.40268488e-11 3.26624686e-05 9.99967337e-01]
 [2.38714620e-06 9.99482989e-01 5.14653570e-04]
 [1.86102661e-05 9.99907374e-01 7.39769457e-05]
 [4.93963416e-05 9.99835014e-01 1.15570379e-04]
 [9.99998689e-01 1.30994067e-06 5.81932986e-19]
 [9.21822539e-06 9.90644574e-01 9.34622809e-03]
 [8.82152472e-06 9.99311090e-01 6.800539